// react hooks
import { useState } from 'react';

// nextjs components/styles
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// MUI components
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';


export default function Home() {

  // normally, I'd *strongly* recommend separating API interaction & rendering layers from each other,
  // but this example is simple enough that we'll just have all the behaviour in one place.
  const BASE_URL = 'https://dummyjson.com/quotes'

  // state variables, just like any variable, can have any type of value! here, we'll use Objects.
  const [quote, setQuote] = useState({
    quote: "Quote goes here.",
    author: "Author name here"
  })

  const handleClick = () => {
    // again, normally I'd separate out API functions, but for the sake of brevity:
    fetch(`${BASE_URL}/random`)
      .then((response) => {
        return response.json()
      }).then((data) => {
        setQuote({
          quote: data.quote,
          author: data.author
        })
      })
  }

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes (and we hate hardcoded data!)
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quote.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quote.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={handleClick}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
