// hooks
import { useState, useEffect } from 'react'

// API functions
import { getRandomQuote } from './api/quotes';

// nextjs/MUI components
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';


export default function Home() {


  const DEFAULT_QUOTE = "Quote here."
  const DEFAULT_AUTHOR = "Author here."

  // We could just increment this by 1 whenever loadNewQuote fires,
  // but: what if multiple parts of logic could write to the same 
  // state variable? Do we want to jump into 29834729384 functions
  // and remember to increment this count in all those places as well?
  // Nope. We can also automate this with useEffect.
  const [quotesCount, setQuotesCount] = useState(0)
  
  const [quoteData, setQuoteData] = useState({
    quote: DEFAULT_QUOTE,
    author: DEFAULT_AUTHOR,
  })

  const loadNewQuote = () => {
    getRandomQuote().then((data)=> {
        setQuoteData({
          quote: data.quote,
          author: data.author
        })
      })
  }

  //loadNewQuote();

  useEffect(
    // param 1: the callback that should fire,
    () => {
      loadNewQuote();
    },

    // param 2: the dependency array
    [] // empty depenency array -> effect fires when page loads
  )

  // in this effect, I can watch 'quoteData' so that whenever it changes,
  // I can fire an effect to auto-increment the quote count.
  useEffect(
    // 1. callback function - logic that runs when effect fires
    ()=> {
      console.log(quoteData)
      if (quoteData.quote !== DEFAULT_QUOTE &&
          quoteData.author !== DEFAULT_AUTHOR) {
        // increment that quote count by 1
        setQuotesCount(quotesCount + 1)
      }
    },
    // 2. dependency array: effect fires on mount, and anytime quoteData changes
    [quoteData]
  )
  // You'll notice when you load the page, it'll say "fetched 2 quotes", when we just expected 1
  // for the initial load. This is because we're using Strict Mode in React, which renders components &
  // fires effects twice for debug purposes.
  // docs: https://react.dev/reference/react/StrictMode#strictmode

  // Gives us better debug/error reporting; just leaving this note here so you don't accidentally go crazy
  // trying to figure out why calls are doubling in your examples/assignments.

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={loadNewQuote}
              >
                Get New Quote
              </Button>
            </Box>

           <Typography
              sx={{pt: 8}}
              variant="h5"
              align="center"
              color="text.primary"
              paragraph
            >
              You have fetched {quotesCount} quotes
            </Typography>

          </Box>
        </Container>
      </main>
    </div>
  )
}
